FROM arm32v7/node:14-slim

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY *.js ./
COPY codecs ./codecs

USER node

EXPOSE 9229

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
