FROM arm64v8/node:14-slim

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY *.js ./
COPY codecs ./codecs

EXPOSE 9229

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
