FROM arm32v7/node:14-alpine

WORKDIR /app/

COPY package*.json ./

RUN npm -version
RUN npm config set unsafe-perm true
RUN npm install --verbose

COPY *.js ./
COPY codecs ./codecs

USER node

EXPOSE 8080

CMD ["node", "app.js"]
